apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "common.labels.standard" . | nindent 8 }}
  ports:
    - port: 5672
      name: rabbitmq-port
      targetPort: 5672
    - port: 15672
      name: rabbitmq-management-port
      targetPort: 15672