apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "common.labels.standard" . | nindent 8 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80